### ISSUE TITLE
init_wallet fails with "NULL json object"

### ISSUE THREAD

**Issue by doriangrosch** [iotaledger/esp32-client-sdk#2]
When executing the project as-is, without modifications, the following error occurs.

I (6212) main: The current date/time is: Mon Nov 15 22:00:20 2021 (1636984820)
I (6212) wallet: Connect to node: api.lb-0.testnet.chrysalis2.com:443 tls:true
[deser_node_info:110] NULL json object
E (8292) wallet: update bech32HRP failed
E (8292) main: Init wallet instance failed

I speculate it has to do with the configured testnet URL. Can anyone replicate this error?

**Comment by oopsmonk** [comment]
the default URL was changed to devnet in Oct.
it might be caused by an old local sdkconfig file or the source is outdated.
1) remove sdkconfig file
2) sync source with upstream
3) re-build project

**Comment by doriangrosch** [comment]
Changing the URL to https://api.lb-0.h.chrysalis-devnet.iota.cafe/ resolved the issue. Thank you.
